import { type NextRequest, NextResponse } from "next/server"

export const runtime = "edge"

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url)
  const videoId = searchParams.get("id")

  if (!videoId) {
    return NextResponse.json({ error: "Video ID is required" }, { status: 400 })
  }

  const apiKey = process.env.YOUTUBE_API_KEY
  if (!apiKey) {
    return NextResponse.json({ error: "YouTube API key not configured" }, { status: 500 })
  }

  try {
    const response = await fetch(
      `https://www.googleapis.com/youtube/v3/captions?videoId=${videoId}&part=snippet&key=${apiKey}`,
    )

    if (!response.ok) {
      throw new Error("Failed to fetch captions from YouTube API")
    }

    const data = await response.json()

    const captions =
      data.items?.map((item: any) => ({
        id: item.id,
        language: item.snippet.language,
        name: item.snippet.name,
        isAutoGenerated: item.snippet.trackKind === "asr",
      })) || []

    return NextResponse.json(captions)
  } catch (error) {
    console.error("YouTube Captions API error:", error)
    return NextResponse.json({ error: "Failed to fetch captions" }, { status: 500 })
  }
}
